spring:
  application:
    name: eureka-consumer-ribbon
  zipkin:
    base-url: http://localhost:9411

server:
  port: 2201

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/