spring:
  application:
    name: eureka-consumer
  zipkin:
    base-url: http://localhost:9411

server:
  port: 2101

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

