spring:
  application:
    name: eureka-client
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1

server:
  port: 2001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/

#management:
#  endpoints:
#    web:
#      exposure:
#        include: heapdump,liquibase,loggers,prometheus,threaddump,info,metrics,health