spring:
  application:
    name: eureka-client

server:
  port: 2001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/

#management:
#  endpoints:
#    web:
#      exposure:
#        include: heapdump,liquibase,loggers,prometheus,threaddump,info,metrics,health